import { readFileSync } from "node:fs";
import type { UserProfile } from "../commands/profile.js";
import type { ProjectAnalysis } from "../analyzers/project.js";
import { profileToMarkdown } from "../commands/profile.js";

export interface GenerateOptions {
  specPath: string;
  agent: string;
  profile: UserProfile;
  analysis: ProjectAnalysis;
}

export function generatePrompt(options: GenerateOptions): string {
  const { specPath, agent, profile, analysis } = options;
  const spec = readFileSync(specPath, "utf-8");
  const lines = spec.split("\n");

  const sections: string[] = [];

  // 1. Header with context
  sections.push(buildHeader(agent, analysis));

  // 2. User profile block
  sections.push(profileToMarkdown(profile));

  // 3. Extract agent-specific section
  const agentSection = extractAgentSection(lines, agent);
  if (agentSection) {
    sections.push(agentSection);
  }

  // 4. Extract universal blocks (A.0 - A.13)
  const universalBlocks = extractUniversalBlocks(lines, analysis);
  sections.push(universalBlocks);

  // 5. Step 0 analysis summary (so the agent knows project context)
  sections.push(buildAnalysisSummary(analysis));

  return sections.join("\n\n---\n\n");
}

function buildHeader(agent: string, analysis: ProjectAnalysis): string {
  return [
    "# Agentic System Initialization Prompt",
    "",
    `> Generated by \`agentinit\` for **${agent}**`,
    `> Project: ${analysis.name}`,
    `> Stack: ${[...analysis.languages, ...analysis.frameworks].join(", ") || "unknown"}`,
    "",
    "Use this prompt to initialize your AI coding agent with project-specific context.",
    "Feed this entire document to your agent at session start.",
  ].join("\n");
}

function extractAgentSection(lines: string[], agent: string): string | null {
  // Map agent IDs to section headers in the spec
  const headerMap: Record<string, string> = {
    "claude-code": "Claude Code",
    cursor: "Cursor",
    codex: "Codex CLI",
    copilot: "GitHub Copilot",
    "gemini-cli": "Gemini CLI",
    cline: "Cline",
    windsurf: "Windsurf",
    "roo-code": "Roo Code",
    "kilo-code": "Kilo Code",
    aider: "Aider",
    generic: "Generic / Agent-Agnostic",
  };

  const targetHeader = headerMap[agent];
  if (!targetHeader) return null;

  let startIdx = -1;
  let endIdx = lines.length;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (
      line.startsWith("## ") &&
      line.toLowerCase().includes(targetHeader.toLowerCase())
    ) {
      startIdx = i;
      continue;
    }
    // End at next ## heading after start
    if (startIdx >= 0 && i > startIdx && line.startsWith("## ")) {
      endIdx = i;
      break;
    }
  }

  if (startIdx < 0) return null;
  return lines.slice(startIdx, endIdx).join("\n");
}

function extractUniversalBlocks(lines: string[], _analysis: ProjectAnalysis): string {
  // Find the universal files / canonical blocks section
  let startIdx = -1;
  let endIdx = lines.length;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (
      line.match(/^#+\s+Universal/i) ||
      line.match(/^#+.*Canonical.*Content.*Blocks/i) ||
      line.match(/^#+.*Block\s+A\.0/i)
    ) {
      if (startIdx < 0) startIdx = i;
    }
    // Stop at major section breaks after universal blocks
    if (startIdx >= 0 && i > startIdx + 10) {
      if (line.match(/^#\s+/) && !line.match(/block|canonical|universal/i)) {
        endIdx = i;
        break;
      }
    }
  }

  if (startIdx < 0) {
    // Fallback: search for "Block A." patterns
    const blockLines: string[] = [];
    let inBlock = false;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]!;
      if (line.match(/^#+\s+Block\s+A\.\d+/i)) {
        inBlock = true;
      } else if (inBlock && line.match(/^#(?!#)/) && !line.match(/block/i)) {
        inBlock = false;
      }
      if (inBlock) blockLines.push(line);
    }
    return blockLines.join("\n");
  }

  return lines.slice(startIdx, endIdx).join("\n");
}

function buildAnalysisSummary(analysis: ProjectAnalysis): string {
  const lines = [
    "## Project Analysis (auto-detected)",
    "",
    `- **Languages:** ${analysis.languages.join(", ") || "not detected"}`,
    `- **Frameworks:** ${analysis.frameworks.join(", ") || "none detected"}`,
    `- **Package manager:** ${analysis.packageManager}`,
    `- **Test framework:** ${analysis.testFramework.join(", ") || "none detected"}`,
    `- **CI/CD:** ${analysis.ci.join(", ") || "none detected"}`,
    `- **Deploy target:** ${analysis.deployTarget.join(", ") || "not detected"}`,
    `- **Docker:** ${analysis.hasDocker ? "yes" : "no"}`,
    `- **Database:** ${analysis.hasDatabase ? "yes" : "no"}`,
    `- **Monorepo:** ${analysis.monorepo ? "yes" : "no"}`,
    "",
    "Use this analysis to inform your initialization decisions.",
  ];
  return lines.join("\n");
}
