import { readFileSync, existsSync } from "node:fs";
import type { UserProfile } from "../commands/profile.js";
import type { ProjectAnalysis } from "../analyzers/project.js";
import { profileToMarkdown } from "../commands/profile.js";
import { loadCdnConfig, type CdnConfig } from "../config.js";
import { fetchAgentAndUniversal } from "../utils/cdn-fetcher.js";

export interface GenerateOptions {
  specPath?: string;
  agent: string;
  profile: UserProfile;
  analysis: ProjectAnalysis;
  offline?: boolean;
  cdnConfig?: Partial<CdnConfig>;
}

export async function generatePrompt(options: GenerateOptions): Promise<string> {
  const { agent, profile, analysis } = options;

  const sections: string[] = [];

  // 1. Header with context
  sections.push(buildHeader(agent, analysis));

  // 2. User profile block
  sections.push(profileToMarkdown(profile));

  // 3 & 4. Get agent section + universal blocks (CDN or local)
  const { agentSection, universalBlocks } = await resolveContent(options);

  if (agentSection) {
    sections.push(agentSection);
  }
  sections.push(universalBlocks);

  // 5. Step 0 analysis summary (so the agent knows project context)
  sections.push(buildAnalysisSummary(analysis));

  return sections.join("\n\n---\n\n");
}

async function resolveContent(
  options: GenerateOptions,
): Promise<{ agentSection: string | null; universalBlocks: string }> {
  const { specPath, agent } = options;

  // If --spec is provided and file exists, use local parsing (backward compat)
  if (specPath && existsSync(specPath)) {
    const spec = readFileSync(specPath, "utf-8");
    const lines = spec.split("\n");
    return {
      agentSection: extractAgentSection(lines, agent),
      universalBlocks: extractUniversalBlocks(lines),
    };
  }

  // Otherwise, fetch from CDN
  const cdnConfig = loadCdnConfig({
    ...options.cdnConfig,
    offline: options.offline ?? options.cdnConfig?.offline,
  });

  const version = getCliVersion();

  try {
    const result = await fetchAgentAndUniversal(agent, version, cdnConfig);
    return {
      agentSection: result.agentSection,
      universalBlocks: result.universalSection,
    };
  } catch (error) {
    // Final fallback: try local spec file in common locations
    const fallbackPaths = [
      "agentic-system-initializer.md",
      "../agentic-system-initializer.md",
    ];
    for (const p of fallbackPaths) {
      if (existsSync(p)) {
        const spec = readFileSync(p, "utf-8");
        const lines = spec.split("\n");
        return {
          agentSection: extractAgentSection(lines, agent),
          universalBlocks: extractUniversalBlocks(lines),
        };
      }
    }
    throw new Error(
      `Could not fetch sections from CDN and no local spec file found. ` +
        `Use --spec to provide a local file, or check your network. (${error instanceof Error ? error.message : error})`,
    );
  }
}

function getCliVersion(): string {
  try {
    const pkg = JSON.parse(readFileSync(new URL("../../package.json", import.meta.url), "utf-8"));
    return pkg.version as string;
  } catch {
    return "0.1.0";
  }
}

function buildHeader(agent: string, analysis: ProjectAnalysis): string {
  return [
    "# Agentic System Initialization — EXECUTE NOW",
    "",
    `> Generated by \`agentinit\` for **${agent}**`,
    `> Project: ${analysis.name}`,
    `> Stack: ${[...analysis.languages, ...analysis.frameworks].join(", ") || "unknown"}`,
    "",
    "## YOUR TASK",
    "",
    "You are an AI coding agent receiving an initialization prompt. **Execute the following steps immediately without asking for confirmation:**",
    "",
    "1. **Read and analyze** the current project directory (files, structure, dependencies)",
    "2. **Install relevant skills** by running: `npx skills add vercel-labs/skills --skill find-skills -y` — then install any skills the find-skills tool recommends for this stack",
    "3. **Generate all configuration files** described in the agent-specific section below (CLAUDE.md, .cursor/rules, AGENTS.md, etc.)",
    "4. **Fill in all `{{placeholder}}` values** using your analysis of the project — do NOT leave unfilled placeholders",
    "5. **Create `.agents/memory/decisions.md`** and seed it with initial architecture decisions based on what you observe",
    "6. **Create custom agents/modes** if the agent platform supports them (e.g., Roo modes, Cursor rules per-glob)",
    "7. **Validate** that all generated files are consistent and complete",
    "",
    "Do NOT ask what to do. Do NOT present options. Just execute the initialization.",
    "",
    "---",
    "",
    "Below is your context: user profile, agent-specific instructions, canonical content blocks, and project analysis.",
  ].join("\n");
}

function extractAgentSection(lines: string[], agent: string): string | null {
  // Map agent IDs to section headers in the spec
  const headerMap: Record<string, string> = {
    "claude-code": "Claude Code",
    cursor: "Cursor",
    codex: "Codex CLI",
    copilot: "GitHub Copilot",
    "gemini-cli": "Gemini CLI",
    cline: "Cline",
    windsurf: "Windsurf",
    "roo-code": "Roo Code",
    "kilo-code": "Kilo Code",
    aider: "Aider",
    generic: "Generic / Agent-Agnostic",
  };

  const targetHeader = headerMap[agent];
  if (!targetHeader) return null;

  let startIdx = -1;
  let endIdx = lines.length;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (
      line.startsWith("## ") &&
      line.toLowerCase().includes(targetHeader.toLowerCase())
    ) {
      startIdx = i;
      continue;
    }
    // End at next ## heading after start
    if (startIdx >= 0 && i > startIdx && line.startsWith("## ")) {
      endIdx = i;
      break;
    }
  }

  if (startIdx < 0) return null;
  return lines.slice(startIdx, endIdx).join("\n");
}

function extractUniversalBlocks(lines: string[]): string {
  // Find the universal files / canonical blocks section
  let startIdx = -1;
  let endIdx = lines.length;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    if (
      line.match(/^#+\s+Universal/i) ||
      line.match(/^#+.*Canonical.*Content.*Blocks/i) ||
      line.match(/^#+.*Block\s+A\.0/i)
    ) {
      if (startIdx < 0) startIdx = i;
    }
    // Stop at major section breaks after universal blocks
    if (startIdx >= 0 && i > startIdx + 10) {
      if (line.match(/^#\s+/) && !line.match(/block|canonical|universal/i)) {
        endIdx = i;
        break;
      }
    }
  }

  if (startIdx < 0) {
    // Fallback: search for "Block A." patterns
    const blockLines: string[] = [];
    let inBlock = false;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]!;
      if (line.match(/^#+\s+Block\s+A\.\d+/i)) {
        inBlock = true;
      } else if (inBlock && line.match(/^#(?!#)/) && !line.match(/block/i)) {
        inBlock = false;
      }
      if (inBlock) blockLines.push(line);
    }
    return blockLines.join("\n");
  }

  return lines.slice(startIdx, endIdx).join("\n");
}

function buildAnalysisSummary(analysis: ProjectAnalysis): string {
  const lines = [
    "## Project Analysis (auto-detected)",
    "",
    `- **Languages:** ${analysis.languages.join(", ") || "not detected"}`,
    `- **Frameworks:** ${analysis.frameworks.join(", ") || "none detected"}`,
    `- **Package manager:** ${analysis.packageManager}`,
    `- **Test framework:** ${analysis.testFramework.join(", ") || "none detected"}`,
    `- **CI/CD:** ${analysis.ci.join(", ") || "none detected"}`,
    `- **Deploy target:** ${analysis.deployTarget.join(", ") || "not detected"}`,
    `- **Docker:** ${analysis.hasDocker ? "yes" : "no"}`,
    `- **Database:** ${analysis.hasDatabase ? "yes" : "no"}`,
    `- **Monorepo:** ${analysis.monorepo ? "yes" : "no"}`,
    "",
    "Use this analysis to inform your initialization decisions.",
  ];
  return lines.join("\n");
}
